services:
  frontend:
    build:
      dockerfile: ./docker/frontend.dockerfile
      target: nginx
    labels:
      - traefik.http.routers.wordle.rule=Host(`wordle.rayzdev.me`)
      - traefik.http.services.wordle.loadbalancer.server.port=80
      - traefik.enable=true
    networks:
      - traefik

networks:
  traefik:
    external: true
